### ISSUE TITLE
mobile version- layout issue

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#181] opened 2018-07-09 20:22 UTC
Front page- headers and buttons are not centered. iPhone X, iOS 11.4, Safari.
![img_0356](https://user-images.githubusercontent.com/40642407/42473987-113c80da-837b-11e8-98f5-da490eba7b11.PNG)

**Comment by kdaily** [comment] 2018-07-18 17:32
duplicate of #182

**Closed by kdaily** 2018-07-18 17:32 UTC
Labels: duplicate
