### ISSUE TITLE
site is unavailble due to certificate issue

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#308] opened 2018-07-18 18:09 UTC
highest priority to fix

**Comment by blogsdon** [comment] 2018-07-18 18:09
<img width="1435" alt="screen shot 2018-07-18 at 11 04 15 am" src="https://user-images.githubusercontent.com/1447157/42899483-046971b8-8a7b-11e8-996e-87f94766836f.png">

**Comment by kdaily** [comment] 2018-07-18 20:08
Duplicate of #98. We will roll back to http.

**Comment by kdaily** [comment] 2018-07-18 22:50
fixed.

**Closed by kdaily** 2018-07-18 22:50 UTC
Labels: high priority
