### ISSUE TITLE
Mobile: Implement mobile menu 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#474] opened 2018-10-24 17:45 UTC
Mobile responsive menu is designed in Figma, please update this.

**Comment by annagree** [comment] 2018-10-25 22:39
https://www.figma.com/file/RAV7geFcRz1qvNjk4XFxRKk6/Agora?node-id=2493%3A253

**Comment by annagree** [comment] 2018-10-25 22:41
duplicate of #463

**Closed by annagree** 2018-10-25 22:41 UTC
Labels: Nov 2018 SFN Milestone, high priority
