### ISSUE TITLE
nominated targets not showing

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#503] opened 2018-10-25 20:32 UTC
<img width="1128" alt="screen shot 2018-10-25 at 1 31 35 pm" src="https://user-images.githubusercontent.com/1447157/47528575-60f31600-d85a-11e8-8cc9-ceaa47b7a1ff.png">

**Comment by annagree** [comment] 2018-10-25 22:18
duplicate of #532

**Closed by annagree** 2018-10-25 22:18 UTC
