### ISSUE TITLE
for genes with no data available in the gene_info.json 

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#260] opened 2018-07-12 17:06 UTC
have a coming soon dialog in the drop down, but don't let the user do anything

**Comment by Zaknarfen** [comment] 2018-07-27 17:41
This would be kinda tricky to do. Can we show a message on the screen? like those closeable messages. Maybe right above the dropdowns? ```A, B, and C: Coming Soon``` with a warning color.

Would this be for models only or do we need this for tissues as well?

**Comment by annagree** [comment] 2018-08-30 02:33
might be duplicate of #344

**Closed** 2018-08-30 16:57 UTC
Labels: low priority
