### ISSUE TITLE
styles for confidence interval on click/hover on dots

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#345] opened 2018-08-15 21:49 UTC
see #249

**Comment by annagree** [comment] 2018-08-16 18:34
@stockards this is one to prioritize for Sprint 1. 
please assign to Diego and Renan when you have the designs completed

**Comment by stockards** [comment] 2018-08-22 18:51
This is a duplicate of #249 I believe. Should we close this one @annagree ?

**Comment by annagree** [comment] 2018-08-22 19:03
Yes- thanks. Closing!

**Closed by annagree** 2018-08-22 19:03 UTC
Labels: design, ui-ux
