### ISSUE TITLE
'nominate a target' results in 404: page missing when

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/Agora#593] opened 2018-11-14 18:56 UTC
To repro':
Go to this page:
https://agora.ampadportal.org
Click on 'nominated targets'.
Click on 'nominate a target'.
Result:  Goes to this address: https://agora.ampadportal.org/nominated-form
The page says "404: page missing"

**Comment by annagree** [comment] 2018-11-14 19:06
Thanks, Bruce- this is a duplicate of #591

**Closed by annagree** 2018-11-14 19:06 UTC
